### ISSUE TITLE
Section 4, st2067-3 reference

### ISSUE THREAD

**Issue by ghost** [imfug/001-timecode-in-imf#1]
RE: Section 4 CompositionTimecode could be construed as ambiguous with no direct reference to how it should be in a CPL, therefore, I feel it may be prudent to reference explicitly, section 8 of st2067-3.

**Comment by mrmxf** [comment]
agreed

**Comment by palemieux** [comment]
Fixed at https://www.imfug.com/TR/DRAFT-timecode-in-imf-20190201/
